# https://bevyengine.org/learn/quick-start/getting-started/setup/
# cranuse for compile time
# [unstable]
# codegen-backend = true

# [profile.dev]
# codegen-backend = "cranelift"

# [profile.dev.package."*"]
# codegen-backend = "llvm"


# Generic Sharing
[target.x86_64-unknown-linux-gnu]
rustflags = [
  # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
]